/*
 * TCSS 305 Assignment 5 - PowerPaint
 */

package gui;

import action.ToolsActions;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 * The GUI class extends from JFrame, setup the GUI layout.
 * 
 * @author Tzu-Chien Lu tclu82@uw.edu
 * @version Nov 20 2015
 */
public class GUI extends JFrame {

    /** A serialVersionUID is generated by Eclipse because extends from JFrame. */
    private static final long serialVersionUID = 3650553337266286532L;
    
    /** A image file is used for window icon. */
    private static final String THE_FILE = "images/gtr2.jpg";
    
    /**
     * Constructor, call its super for JFrame and setup the title.
     * Calls helper method setup.
     */
    public GUI() {
        super("PowerPaint");
        setup();    
    }
    
    /**
     * setup method create all components for painting.
     */
    private void setup() {
        final GUIPanel panel = new GUIPanel();
        final ToolsActions ta = new ToolsActions(panel);
        final GUIMenuBar ma = new GUIMenuBar(ta.getActions(), this, panel);
        final GUIToolBar tb = new GUIToolBar(ta.getActions());
  
        /** Add GUIMenuBar to this GUI.*/
        setJMenuBar(ma);
        
        /** Read image from images folder. */
        Image pic = null;
        
        try {
            /** My favorite car. */
            pic = ImageIO.read(new File(THE_FILE));
        
        } catch (final IOException ioe) {
            ioe.printStackTrace();
        }
        
        /** Set this picture as icon image. */
        setIconImage(pic);
        
        /** Add tool bar and panel to this frame. */
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        add(tb, BorderLayout.SOUTH);
        
        /** Add scroll to JPanel. */
        final JScrollPane jcp = new JScrollPane(panel);   
        add(jcp, BorderLayout.CENTER);
        
        /** Pack all components. */
        pack();
        
        /** Set center and visible.*/
        setLocationRelativeTo(null);
        setVisible(true);
    }
}
