/*
 * TCSS 305 Assignment 5 - PowerPaint
 */

package gui;

import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;

/**
 * The ToolBar class.
 *
 * @author Tzu-Chien Lu tclu82@uw.edu
 * @version Nov 20 2015
 */
public class GUIToolBar extends JToolBar {

    /** A serialVersionUID is generated by Eclipse because extends from JToolBar. */
    private static final long serialVersionUID = 4268951943328073987L;
    
    /** A ButtonGroup is used to contain buttons. */
    private final ButtonGroup myToggleBottonGroup;
    
    /**
     * Constructor for ToolBar class.
     * 
     * @param theActions a List of Action.
     */
    public GUIToolBar(final Action[] theActions) {
        super();
        myToggleBottonGroup = new ButtonGroup();
        
        /** For all actions, use helper method to add a JToggleButton. */
        for (final Action a: theActions) {
            add(createToolButton(a));
        }
        
        /** Clear the button selection. */
        myToggleBottonGroup.clearSelection();
    }
    
    /**
     * Create a JToogleButton, attach Listener to a it, and add it into JToggleButton group.
     * 
     * @param theAction An action.
     * @return A JToggleButton is used for return.
     */
    private JToggleButton createToolButton(final Action theAction) {
        final JToggleButton tb = new JToggleButton(theAction);
        tb.addActionListener(theAction);
        myToggleBottonGroup.add(tb);
        return tb;
    }
}
